# ZAGRIO WebHosting
# https://www.zagrio.com/
# Updates IIS bindings across all sites by replacing all IP addresses from $oldIP to $newIP.
$OldIP = "1.1.1.1"
$NewIP = "2.2.2.2"
foreach ($Website in Get-Website) {
    "Site: {0}" -f $Website.name
    $Bindings = Get-WebBinding -Name $Website.name
    foreach ($Binding in $Website.bindings.Collection) {
        $BindingInfo = $Binding.bindingInformation
        "    Binding: {0}" -f $BindingInfo
        if ($BindingInfo -imatch $OldIP) {
            "        Updating IP: {0} ---> {1}" -f $OldIP, $NewIP
            Set-WebBinding -Name $Website.name -BindingInformation $BindingInfo -PropertyName "IPAddress" -Value $NewIP -Verbose
            Write-Host -ForegroundColor Green "The site $Website IP changed from $OldIP to $NewIP"
        }
    }
}
# SIG # Begin signature block
# MIIKVwYJKoZIhvcNAQcCoIIKSDCCCkQCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAbmN3Al4Mh6jVf
# FSuDQIlREj/P3XVT4tONk/QWhNJCS6CCCAAwggOrMIICk6ADAgECAhB3iG/eaHjQ
# sEt612mH+yCRMA0GCSqGSIb3DQEBDQUAMFwxEzARBgoJkiaJk/IsZAEZFgNjb20x
# FjAUBgoJkiaJk/IsZAEZFgZ6YWdyaW8xFTATBgoJkiaJk/IsZAEZFgVpcndpbjEW
# MBQGA1UEAxMNSVJXSU4tUk9PVC1DQTAeFw0xODA5MDYxMTEyNDFaFw0zODA5MDYx
# MTIyNDBaMFwxEzARBgoJkiaJk/IsZAEZFgNjb20xFjAUBgoJkiaJk/IsZAEZFgZ6
# YWdyaW8xFTATBgoJkiaJk/IsZAEZFgVpcndpbjEWMBQGA1UEAxMNSVJXSU4tUk9P
# VC1DQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOj7EKNssA4ryjg6
# xh1nPv62YsGYj3h/7SmSFpBprkiTYmGmzduMdO5TTXeqKkVUFpPSEhCxFd7FjTAU
# dxqhNsFG8kzFlpXrrMGDS/30kFdzyHn7SqrR/K/wwIz6QWFpQl6fDgUmwrK8+23N
# Yjg/I2GWmE81TC5Qje9IOSUq91hoGcVHSpTAUTPeU4soIxpIcagHbLse7waxB7I8
# 1yjEt6Q8bxfG5csayXhbJCLpRWXyR6NohJ6Cw/n/mNEaBvjFVF/w5lTq94UnB7/S
# 8EQyXn4YgtDTmbIvK5VBv8B1/UK7khwlbF74tjfIwy/MyMVXEQYRcNMfNlEZMFUj
# VAfFa2sCAwEAAaNpMGcwEwYJKwYBBAGCNxQCBAYeBABDAEEwDgYDVR0PAQH/BAQD
# AgGGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFHaVF43v7v+He6mLk2VgUkmW
# UyCDMBAGCSsGAQQBgjcVAQQDAgEAMA0GCSqGSIb3DQEBDQUAA4IBAQCEL4WgFa8/
# cEghr+LTE7xBeC4C6FcY28eRR4jKHDfUiKA6L+l3JM92vwJMdut+y8JKzP0R39Ij
# jXGrCzecnKxKnQb0QZdsRkaE45K5odpnER4h4DK6OQl9G29NYVFq2UJzOucwZUZU
# Xsl8R9AbgfDEzk1OkcOpJMYjVaPi5ZqL6xIIK/6m3kHUVpzxeeEBajhyDEPd2RyY
# rB8qcbmJ4Pzm5dvdVSowU0rQlMbMPBslQlOlNPxmh3pE6crdxaKwGzbEUVMIZFtb
# WsRuVq52RKKm88WSidHQl7ew2b5ua8lWDI6xGKvHxyqThVoCBQ5bDM8jlXRM+mDI
# igQqejoTwKXLMIIETTCCAzWgAwIBAgITGwAACOh+B8NfYD2sugAAAAAI6DANBgkq
# hkiG9w0BAQ0FADBcMRMwEQYKCZImiZPyLGQBGRYDY29tMRYwFAYKCZImiZPyLGQB
# GRYGemFncmlvMRUwEwYKCZImiZPyLGQBGRYFaXJ3aW4xFjAUBgNVBAMTDUlSV0lO
# LVJPT1QtQ0EwHhcNMjIwMTA2MDA0OTMzWhcNMjcwMTA1MDA0OTMzWjBwMRMwEQYK
# CZImiZPyLGQBGRYDY29tMRYwFAYKCZImiZPyLGQBGRYGemFncmlvMRUwEwYKCZIm
# iZPyLGQBGRYFaXJ3aW4xDjAMBgNVBAMTBVVzZXJzMRowGAYDVQQDExFNb2hhbW1h
# ZCBTaGFkbWFuaTCBmzAQBgcqhkjOPQIBBgUrgQQAIwOBhgAEACRnk7xQ3/BkQZcs
# 1XwofpzL997FhldgkMXln4AEmpuMoNvkFhbRI6oVFKFHqyM5i5DnMX/dvXYM+irB
# +8KeGxLwAF2J1wjDwe5fMf4moLEShrHK6VcNfrnqxkq4COJ3DkHXiHDvKlYchq6K
# GmBEu2gOg4SgcP6MdYMVs7fcKCdsPPe2o4IBejCCAXYwPAYJKwYBBAGCNxUHBC8w
# LQYlKwYBBAGCNxUIg9/vQIaluV+5gSGE6q4Dg4KvbDKGsqRhh9CDQwIBZAIBCTAT
# BgNVHSUEDDAKBggrBgEFBQcDAzAOBgNVHQ8BAf8EBAMCB4AwGwYJKwYBBAGCNxUK
# BA4wDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQUcaq06JjraRipPwa380CFdJlPH70w
# HwYDVR0jBBgwFoAUdpUXje/u/4d7qYuTZWBSSZZTIIMwQQYDVR0fBDowODA2oDSg
# MoYwaHR0cDovL2NhLmlyd2luLnphZ3Jpby5jb20vY3JsL0lSV0lOLVJPT1QtQ0Eu
# Y3JsMDsGCCsGAQUFBwEBBC8wLTArBggrBgEFBQcwAYYfaHR0cDovL0NBLklSV0lO
# LlpBR1JJTy5DT00vT0NTUDA0BgNVHREELTAroCkGCisGAQQBgjcUAgOgGwwZbW9o
# YW1tYWRAaXJ3aW4uemFncmlvLmNvbTANBgkqhkiG9w0BAQ0FAAOCAQEA07VANGwr
# DdQovAx1QlNtdJK7yVidqek64MpHBxZa4FVpEHbl7NDKRnSVsss3iBtNQH8GMA2k
# LWD7KKI6W0g9jqlBEisMlEe597Iq4wumo02QMxo0NIX/FBStVXO4y9elr0Fe495a
# dzzG75hf8dRqViV3txBdFebjuniAEOMWGhEbm0RKi4SliwYxdYwUvBcm0m6VHZaX
# 7xUnLDa49ilr+wYHalg1Y+JoXDI643W89YRy87XM4Gm6Zbg0JwJKHoLgPaX0ui98
# lB2TF0i+ZGRVWLG+Pu4Lj9/TSWvhP2gJG7kiebFLBJRlkPQLaUy1ecaeUvw9BMAm
# vZKMjBoSY6M0ODGCAa0wggGpAgEBMHMwXDETMBEGCgmSJomT8ixkARkWA2NvbTEW
# MBQGCgmSJomT8ixkARkWBnphZ3JpbzEVMBMGCgmSJomT8ixkARkWBWlyd2luMRYw
# FAYDVQQDEw1JUldJTi1ST09ULUNBAhMbAAAI6H4Hw19gPay6AAAAAAjoMA0GCWCG
# SAFlAwQCAQUAoIGEMBgGCisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcN
# AQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUw
# LwYJKoZIhvcNAQkEMSIEIEQrlclwkqhFLok+4PcGRz/9QqwtLrF+KQb+yFODt7ew
# MAsGByqGSM49AgEFAASBizCBiAJCARXvqBE9dlHbmpMX9MRAjnxO6Azp/bt+i5zk
# ZNSV8eFYri2TyOo9akIYGNqLvCxAzvIxlYQ0pKkT2o7s0YUs3dmRAkIBBe5/Lq7b
# XuKkDRvoEt073JHEqr/f0yQOjPrDy9BJhX0lRBydIbTskvod+XJchUwF6M+JsfDl
# BEbM2GglmrToM6Q=
# SIG # End signature block
